version: '3.5'

services:
  db:
    container_name: reddit_db
    image: postgres
    restart: always

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  reddit:
    container_name: reddit_app
    build: .

    ports:
      - 8082:8080

    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_HOST: db
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_SECRET_KEY: ${CLOUDINARY_SECRET_KEY}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}

    depends_on:
      - db

    links:
      - db


  nginx:
    image: custom_nginx
    container_name: custom_nginx
    depends_on:
      - reddit
    ports:
      - 80:80

networks:
  default:
    external:
      name: reddit_network