CREATE SEQUENCE user_sequence START 1 INCREMENT 1;
CREATE SEQUENCE post_sequence START 1 INCREMENT 1;
CREATE SEQUENCE comment_sequence START 1 INCREMENT 1;
CREATE SEQUENCE categories_sequence START 1 INCREMENT 1;

